[uwsgi]
# Who will run the code
uid = searxng
gid = searxng

# Number of workers (usually 2-4 x $(nproc))
workers = 4
threads = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpreter config
single-interpreter = true
master = true
plugin = python3
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python home
virtualenv = /usr/local/searxng-pyenv
pythonpath = /usr/local/searxng/searxng-src

# Free memory and GC on every request
harakiri = 60
harakiri-verbose = true
reaper = true
vacuum = true

# Disable logging for privacy
disable-logging = true
